# Generated by Django 5.0 on 2023-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Комиксы',
                'verbose_name_plural': 'Комиксы',
            },
        ),
    ]
